SopEmbraco/ViewModels/DigitalSopViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SopEmbraco.ViewModels
{
    public class DigitalSopViewModel
    {
        [Required]
        public Guid WorkshopId { get; set; }
        public Guid? ProductModelId { get; set; }
        [Required]
        public Guid ProductCodeId { get; set; }
        [Required]
        public Guid WorkshopLineId { get; set; }
        public int? Position { get; set; }

        public List<FileViewModel> Files { get; set; } = new List<FileViewModel>();
    }
}

SopEmbraco/Controllers/DigitalSopController.cs
using SopEmbraco.Models;
using SopEmbraco.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using System.Configuration;
using SopEmbraco.Infrastructure;

namespace SopEmbraco.Controllers
{
    public class DigitalSopController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private string directoryFiles = ConfigurationManager.AppSettings["DirectoryFiles"];
        private string domain = ConfigurationManager.AppSettings["Domain"];
        private string username = ConfigurationManager.AppSettings["Username"];
        private string password = ConfigurationManager.AppSettings["Password"];

        // GET: DigitalSop
        public ActionResult Index()
        {
            
            ViewBag.Workshops = db.Workshops.OrderBy(ws => ws.Name);
            ViewBag.ProductCodes = new List<ProductCode>().OrderBy(pc=> pc.Workshop.Name).ThenBy(pc=> pc.Name);
            ViewBag.ProductModels = db.ProductModels.ToList().OrderBy(pm=> pm.Name);
            ViewBag.WorkshopLines = new List<WorkshopLine>().OrderBy(wl=> wl.Workshop.Name).ThenBy(wl=> wl.Name);
            ViewBag.Positions = new List<SelectListItem>();
            return View();
        }

        public ActionResult GetFiles()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult GetFiles(DigitalSopViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var workshopLine = db.WorkshopLines.FirstOrDefault(w => w.WorkshopLineId == viewModel.WorkshopLineId);
                var productCode = db.ProductCodes.Include(pc => pc.ProductModel).FirstOrDefault(p => p.ProductCodeId == viewModel.ProductCodeId);
                var path = directoryFiles + "/" + workshopLine.Workshop.Name + "/" + productCode.ProductModel.Name + "/" + productCode.Name + "/" + workshopLine.Name;

                WrapperImpersonationContext context = new WrapperImpersonationContext(domain, username, password);
                context.Enter();
                var d = new DirectoryInfo(path);
                var files = d.GetFiles("*.*");

                if (viewModel.Position != null)
                {
                    var file = files.FirstOrDefault(f => f.Name == viewModel.Position.ToString() + ".pdf");
                    if (file != null)
                    {
                        viewModel.Files.Add(new FileViewModel
                        {
                            Name = file.Name,
                            ProductCodeId = viewModel.ProductCodeId,
                            WorkshopLineId = viewModel.WorkshopLineId
                        });
                    }
                    else
                    {
                        file = files.FirstOrDefault(f => f.Name == viewModel.Position.ToString() + ".jpg");
                        if (file != null)
                        {
                            viewModel.Files.Add(new FileViewModel
                            {
                                Name = file.Name,
                                ProductCodeId = viewModel.ProductCodeId,
                                WorkshopLineId = viewModel.WorkshopLineId
                            });
                        }
                    }
                }
                else
                {
                    foreach (FileInfo file in files)
                    {
                        viewModel.Files.Add(new FileViewModel
                        {
                            Name = file.Name,
                            ProductCodeId = viewModel.ProductCodeId,
                            WorkshopLineId = viewModel.WorkshopLineId
                        });
                    }
                }
                context.Leave();
            }

            ViewBag.Workshops = db.Workshops;
            if (viewModel.WorkshopId != null)
            {
                ViewBag.ProductCodes = db.ProductCodes.Where(pc => pc.WorkshopId == viewModel.WorkshopId);
                ViewBag.WorkshopLines = db.WorkshopLines.Where(wl => wl.WorkshopId == viewModel.WorkshopId);

                if (viewModel.WorkshopLineId == null) ViewBag.Positions = new List<SelectListItem>();
                var workshopLine = db.WorkshopLines.FirstOrDefault(w => w.WorkshopLineId == viewModel.WorkshopLineId);
                if (workshopLine == null) ViewBag.Positions = new List<SelectListItem>();

                ViewBag.Positions = Enumerable.Range(1, workshopLine.Positions)
                    .Select(p => new SelectListItem
                    {
                        Text = p.ToString(),
                        Value = p.ToString(),
                        Selected = p == viewModel.Position
                    })
                    .ToList();
            }
            else
            {
                ViewBag.ProductCodes = new List<ProductCode>();
                ViewBag.WorkshopLines = new List<WorkshopLine>();
                ViewBag.Positions = new List<SelectListItem>();
            }

            ViewBag.ProductModels = db.ProductModels.ToList();
            return View("Index", viewModel);
        }

        public ActionResult Download(Guid ProductCodeId, Guid WorkshopLineId, String fileId)
        {

            var workshopLine = db.WorkshopLines.FirstOrDefault(w => w.WorkshopLineId == WorkshopLineId);
            var productCode = db.ProductCodes.FirstOrDefault(p => p.ProductCodeId == ProductCodeId);

            WrapperImpersonationContext context = new WrapperImpersonationContext(domain, username, password);
            context.Enter();
            byte[] file = System.IO.File.ReadAllBytes(
                Path.Combine(directoryFiles + workshopLine.Workshop.Name + "/" + productCode.ProductModel.Name + "/" + productCode.Name + "/" + workshopLine.Name,
                fileId));

            return File(file, System.Net.Mime.MediaTypeNames.Application.Octet, fileId);
        }

    }
}

SopEmbraco/Views/DigitalSop/Index.cshtml
@model SopEmbraco.ViewModels.DigitalSopViewModel
@using SopEmbraco.Models

@using (Html.BeginForm("GetFiles", "DigitalSop"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Digital SOP</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.WorkshopId, "生产车间", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.WorkshopId, ((IEnumerable<Workshop>)ViewBag.Workshops).Select(option => new SelectListItem
                {
                    Text = option.Name,
                    Value = option.WorkshopId.ToString(),
                    Selected = (Model != null) && (Model.WorkshopId == option.WorkshopId)
                }),
             "Select...", htmlAttributes: new { @class = "form-control bigComboBox" })
                @Html.ValidationMessageFor(model => model.WorkshopId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductModelId, "产品家族", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProductModelId, ((IEnumerable<ProductModel>)ViewBag.ProductModels).Select(option => new SelectListItem
                {
                    Text = option.Name,
                    Value = option.ProductModelId.ToString(),
                    Selected = (Model != null) && (Model.ProductModelId == option.ProductModelId)
                }), htmlAttributes: new { @class = "form-control bigComboBox" })
                @Html.ValidationMessageFor(model => model.ProductModelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductCodeId, "生产型号", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProductCodeId, ((IEnumerable<ProductCode>)ViewBag.ProductCodes).Select(option => new SelectListItem
                {
                    Text = option.Name,
                    Value = option.ProductCodeId.ToString(),
                    Selected = (Model != null) && (Model.ProductCodeId == option.ProductCodeId)
                }),
             "Select...", htmlAttributes: new { @class = "form-control bigComboBox" })
                @Html.ValidationMessageFor(model => model.ProductCodeId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.WorkshopLineId, " 生产线别", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.WorkshopLineId, ((IEnumerable<WorkshopLine>)ViewBag.WorkshopLines).Select(option => new SelectListItem
                {
                    Text = option.Name,
                    Value = option.WorkshopLineId.ToString(),
                    Selected = (Model != null) && (Model.WorkshopLineId == option.WorkshopLineId)
                }), "Select...", htmlAttributes: new { @class = "form-control bigComboBox" })
                @Html.ValidationMessageFor(model => model.WorkshopId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Position, "位置（可选）", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Position, ((List<SelectListItem>)ViewBag.Positions),
             "All Positions", htmlAttributes: new { @class = "form-control bigComboBox" })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@if (Model != null && Model.Files != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>Position File</th>
                <th>Link</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Files)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>[ <a href="~/DigitalSop/Download/?FileId=@(item.Name)&WorkshopLineId=@(item.WorkshopLineId)&ProductCodeId=@(item.ProductCodeId)">Download</a> ]</td>
                </tr>
            }
        </tbody>
    </table>
}

@section Scripts {
    <script>
        function ReloadProductCodes(workshopId, productModelId) {
            if (workshopId == "") return;
            $("#ProductCodeId").attr('disabled', true);
            var queryProductModel = "";
            if (productModelId != "") queryProductModel = "?ProductModelId=" + productModelId;

            $.ajax({
                url: "@Url.Action("SelectByWorkshopId","ProductCodes")" + "/" + workshopId + queryProductModel,
                success: function (data) {
                    $("#ProductCodeId").empty();
                    $("#ProductCodeId").append('<option value>Select...</option>');
                    $.each(data, function (index, element) {
                        $("#ProductCodeId").append('<option value="' + element.ProductCodeId + '">' + element.Name + '</option>');
                    });

                    $("#ProductCodeId").attr('disabled', false);
                }
            });
        }

        function ReloadWorkshopLines(workshopId) {
            if (workshopId == "") return;
            $("#WorkshopLineId").attr('disabled', true);

            $.ajax({
                url: "@Url.Action("SelectByWorkshopId","WorkshopLines")" + "/" + workshopId,
                success: function (data) {
                    $("#WorkshopLineId").empty();
                    $("#WorkshopLineId").append('<option value>Select...</option>');
                    $.each(data, function (index, element) {
                        $("#WorkshopLineId").append('<option value="' + element.WorkshopLineId + '">' + element.Name + '</option>');
                    });

                    $("#WorkshopLineId").attr('disabled', false);
                }
            });
        }

        function ReloadPositions(workshopLineId) {
            $("#Position").attr('disabled', true);

            $.ajax({
                url: "@Url.Action("Get","WorkshopLines")" + "/" + workshopLineId,
                success: function (data) {
                    $("#Position").empty();
                    $("#Position").append('<option value>All Positions</option>');
                    for (i = 1; i <= data.Positions; i++) {
                        $("#Position").append('<option value="' + i + '">' + i + '</option>');
                    };

                    $("#Position").attr('disabled', false);
                }
            });
        }

        $("#WorkshopId").change(function () {
            ReloadProductCodes($(this).val(), $("#ProductModelId").val());
            ReloadWorkshopLines($(this).val());
        });

        $("#WorkshopLineId").change(function () {
            ReloadPositions($(this).val());
        });

        $("#ProductModelId").change(function () {
            ReloadProductCodes($("#WorkshopId").val(), $(this).val());
            ReloadWorkshopLines($("#WorkshopId").val());
        });
    </script>
}