SopEmbraco/Models/Production.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SopEmbraco.Models
{
    public class Production : IValidatableObject
    {
        [Key]
        public Guid ProductionId { get; set; }
        public Guid ProductionBatchId { get; set; }
        public Guid WorkshopLineId { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; } = DateTime.Now;
        [Required]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public TimeSpan StartTime { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public TimeSpan EndTime { get; set; }
        [Required]
        public int Target { get; set; }
        [Required]
        public int RealQuantity { get; set; }
        [DataType(DataType.MultilineText)]
        public String Comment { get; set; }

        [NotMapped]
        public String ProductCodeName { get; set; }
        [NotMapped]
        public String PlanQuantity { get; set; }
        [NotMapped]
        public bool ProductionBatchStatusConcluded { get; set; }
        [NotMapped]
        public String ConcludedBatchName { get; set; }

        public virtual ProductionBatch ProductionBatch { get; set; }
        public virtual WorkshopLine WorkshopLine { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (RealQuantity < Target && String.IsNullOrEmpty(Comment))
            {
                yield return new ValidationResult("Please justify the difference between the amount of Target and Real Quantity produced.",
                    new[] { "Comment" });
            }
        }
    }
}

SopEmbraco/ViewModels/ProductionViewModel.cs
using SopEmbraco.Models;
using System;
using System.Collections.Generic;

namespace SopEmbraco.ViewModels
{
    public class ProductionViewModel
    {
        public Guid WorkshopId { get; set; }
        public Guid WorkshopLineId { get; set; }
        public Guid? ProductCodeId { get; set; }
        public Guid? ProductModelId { get; set; }
        public Guid? ProductionBatchId { get; set; }

        public DateTime? ProductionDate { get; set; }

        public virtual ICollection<Production> ConcludedProductions { get; set; }
        public virtual ICollection<Production> PendingProductions { get; set; }
        public virtual WorkshopLine WorkshopLine { get; set; }
    }
}

SopEmbraco/ViewModels/ReportsViewModel.cs
using SopEmbraco.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SopEmbraco.ViewModels
{
    public class ReportsViewModel
    {
        public Guid WorkshopId { get; set; }
        public DateTime Date { get; set; }

        public virtual ICollection<ReportsWorkshopLineViewModel> WorkshopLineReports { get; set; }
    }
}

SopEmbraco/Controllers/ProductionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using SopEmbraco.Models;
using SopEmbraco.ViewModels;
using SopEmbraco.Infrastructure.Helpers;
using OfficeOpenXml;

namespace SopEmbraco.Controllers
{
    public class ProductionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            ViewBag.Workshops = db.Workshops.ToList();
            ViewBag.WorkshopLines = db.WorkshopLines.ToList(); // new SelectList(db.WorkshopLines, "WorkshopLineId", "Name");
            ViewBag.ProductModels = db.ProductModels.ToList(); // new SelectList(db.ProductModels.OrderBy(m => m.Name), "ProductModelId", "Name");
            ViewBag.ProductCodes = db.ProductCodes.ToList(); // new SelectList(db.ProductCodes.OrderBy(pc => pc.Name), "ProductCodeId", "Name");
            ViewBag.ProductionBatches = db.ProductionBatches.ToList();
            return View();
        }

        public ActionResult Report()
        {
            ViewBag.Workshops = db.Workshops.ToList();
            ViewBag.WorkshopLines = db.WorkshopLines.ToList();
            ViewBag.ProductModels = db.ProductModels.ToList();
            ViewBag.ProductCodes = db.ProductCodes.ToList();
            ViewBag.ProductionBatches = db.ProductionBatches.ToList();
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> IndexJson(ProductionViewModel viewModel)
        {
            var query = db.Productions.AsQueryable();

            if (viewModel.WorkshopLineId != null)
            {
                query = query.Where(p => p.WorkshopLineId == viewModel.WorkshopLineId);
            }

            if (viewModel.ProductionDate != null)
            {
                query = query.Where(p => p.Date == viewModel.ProductionDate);
            }

            if (viewModel.ProductModelId != null)
            {
                query = query.Where(p => p.ProductionBatch.ProductCode.ProductModelId == viewModel.ProductModelId);
            }
            if (viewModel.ProductCodeId != null)
            {
                query = query.Where(p => p.ProductionBatch.ProductCodeId == viewModel.ProductCodeId);
            }
            if (viewModel.ProductionBatchId != null)
            {
                query = query.Where(p => p.ProductionBatchId == viewModel.ProductionBatchId);
            } 

           // query = query.Where(p => p.ProductionBatch.Status == Enums.ProductionBatchStatus.Open);

            return Json(await query.Select(p => new
            {
                Comment = p.Comment,
                Date = p.Date,
                EndTime = p.EndTime,
                ProductionBatchId = p.ProductionBatchId,
                ProductionId = p.ProductionId,
                RealQuantity = p.RealQuantity,
                StartTime = p.StartTime,
                Target = p.Target,
                WorkshopLineId = p.WorkshopLineId,
                PlanQty = p.ProductionBatch.Quantity.ToString(),
                ProductCodeName = p.ProductionBatch.ProductCode.Name.ToString()
            }).ToListAsync(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<JsonResult> ReportJson(ProductionReportViewModel viewModel)
        {
            var query = BuildReportQuery(viewModel);

            return Json(await query.Select(p => new
            {
                Comment = p.Comment,
                Date = p.Date,
                EndTime = p.EndTime,
                ProductionBatchId = p.ProductionBatchId,
                ProductionId = p.ProductionId,
                RealQuantity = p.RealQuantity,
                StartTime = p.StartTime,
                Target = p.Target,
                WorkshopLineId = p.WorkshopLineId,
                PlanQty = p.ProductionBatch.Quantity.ToString(),
                ProductCodeName = p.ProductionBatch.ProductCode.Name.ToString()
            }).ToListAsync(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> CreateJson([Bind(Include = "ProductionBatchId,PlanQty,ProductCode,Date,StartTime,EndTime,WorkshopLineId,Target,RealQuantity,Comment")] Production production)
        {
            if (ModelState.IsValid)
            {
                production.ProductionId = Guid.NewGuid();
                db.Productions.Add(production);
                await db.SaveChangesAsync();
                return Json(production, JsonRequestBehavior.DenyGet);
            }

            /* foreach (ModelState modelState in ViewData.ModelState.Values)
            {
                foreach (ModelError error in modelState.Errors)
                {
                    DoSomethingWith(error);
                }
            } */

            return Json(new { Status = "Failure" }, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        public async Task<JsonResult> EditJson([Bind(Include = "ProductionId,ProductionBatchId,PlanQty,ProductCode,Date,StartTime,EndTime,WorkshopLineId,Target,RealQuantity,Comment")] Production production)
        {
            if (ModelState.IsValid)
            {
                db.Entry(production).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return Json(production, JsonRequestBehavior.DenyGet);
            }

            return Json(new { Status = "Failure" }, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        public async Task<JsonResult> DeleteJson([Bind(Include = "ProductionId")] Production production)
        {
            Production productionDb = await db.Productions.FirstOrDefaultAsync(p => p.ProductionId == production.ProductionId);
            db.Productions.Remove(productionDb);
            await db.SaveChangesAsync();
            return Json(new { Status = "Ok" }, JsonRequestBehavior.DenyGet);
        }

        // GET: Productions/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Production production = await db.Productions.Include(p => p.WorkshopLine.Workshop).Include(p => p.WorkshopLine.Productions).FindAsync(id);
            WorkshopLine workshopLine = await db.WorkshopLines.Include(wl => wl.Productions).FirstOrDefaultAsync(wl => wl.WorkshopLineId == id);
            if (workshopLine == null)
            {
                return HttpNotFound();
            }
            return View(workshopLine);
        }

        // GET: Productions/Create
        public ActionResult Create()
        {
            ViewBag.ProductionBatches = db.ProductionBatches.Where(pb => pb.Status != Enums.ProductionBatchStatus.Concluded).ToList();

            ViewBag.Workshops = db.Workshops.ToList();
            ViewBag.WorkshopLineId = new SelectList(db.WorkshopLines, "WorkshopLineId", "Name");
            var productions = new List<Production>();

            foreach (var timeSuggestion in db.TimeSuggestions.OrderBy(t => t.StartTime))
            {
                productions.Add(new Production {
                    StartTime = timeSuggestion.StartTime,
                    EndTime = timeSuggestion.EndTime
                });
            }
            return View(new ProductionViewModel
            {
                PendingProductions = productions
            });
        }

        // POST: Productions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductionViewModel viewModel, FormCollection formCollection)
        {
            ViewBag.ProductionBatches = db.ProductionBatches.Where(pb => pb.Status != Enums.ProductionBatchStatus.Concluded).ToList();
            ViewBag.Workshops = db.Workshops.ToList();
            ViewBag.WorkshopLineId = new SelectList(db.WorkshopLines, "WorkshopLineId", "Name", viewModel.WorkshopLineId);

            if (ModelState.IsValid)
            {
                // Collision detection
                Production previousProduction = null;
                bool collisions = false;

                // TODO: Convert FormCollection items to typed classes to perform a decent validation. 

                foreach (var productionGroup in viewModel.PendingProductions.OrderBy(p => p.StartTime).GroupBy(p => new { p.Date, p.ProductionBatchId }))
                {
                    foreach (var production in productionGroup)
                    {
                        if (previousProduction == null)
                        {
                            previousProduction = production;
                            continue;
                        }

                        if (production.StartTime < previousProduction.EndTime)
                        {
                            ModelState.AddModelError("", "Time Collision Detected: End Time: " + previousProduction.EndTime + "; Start Time: " + production.StartTime + ";");
                            collisions = true;
                        }

                        previousProduction = production;
                    }

                    previousProduction = null;
                }

                if (collisions) return View(viewModel);

                foreach (var production in viewModel.PendingProductions)
                {
                    production.WorkshopLineId = viewModel.WorkshopLineId;
                    production.ProductionId = Guid.NewGuid();
                    db.Productions.Add(production);
                }

                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // GET: Productions/Edit/5
        public async Task<ActionResult> Edit(Guid? id, DateTime? ReferenceDate)
        {
            if (id == null)

SopEmbraco/Views/Productions/Create.cshtml
@model SopEmbraco.ViewModels.ProductionViewModel
@using SopEmbraco.Models

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Productions</h4>
        <hr />

        @Html.ValidationSummary(false, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.WorkshopId, "WorkshopId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.WorkshopId, ((IEnumerable<Workshop>)ViewBag.Workshops).Select(option => new SelectListItem
                {
                    Text = option.Name,
                    Value = option.WorkshopId.ToString()
                }), "All", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WorkshopId, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.WorkshopLineId, "WorkshopLineId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("WorkshopLineId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WorkshopLineId, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.Partial("_CreateOrEdit", Model)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a id="add-new-production" class="btn btn-default">Add Line</a>
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function ReloadWorkshopLines(workshopId) {
            if (workshopId == "") return;
            $("#WorkshopLineId").attr('disabled', true);

            $.ajax({
                url: "@Url.Action("SelectByWorkshopId","WorkshopLines")" + "/" + workshopId,
                success: function (data) {
                    $("#WorkshopLineId").empty();
                    $("#WorkshopLineId").append('<option value>Select...</option>');
                    $.each(data, function (index, element) {
                        $("#WorkshopLineId").append('<option value="' + element.WorkshopLineId + '">' + element.Name + '</option>');
                    });

                    $("#WorkshopLineId").attr('disabled', false);
                }
            });
        }

        $(document).on("change", ".productionbatch", function () {
            var selectedBatch = $(this);
            $.ajax({
                url: "@Url.Action("GetProductCodeJson", "ProductionBatches")" + "/" + $(this).val(),
                success: function (data) {
                    var productCodeId = "#" + $(selectedBatch).attr('id').replace("ProductionBatchId", "ProductCodeName");
                    var planQuantityId = "#" + $(selectedBatch).attr('id').replace("ProductionBatchId", "PlanQuantity");
                    var targetId = "#" + $(selectedBatch).attr('id').replace("ProductionBatchId", "Target");
                    $(productCodeId).val(data.Name);
                    $(planQuantityId).val(data.Quantity);
                    $(targetId).val(data.Target);
                }
            });
        });

        $("#add-new-production").click(function () {
            $.get("@Url.Action("NewProductionRow", "Productions")", function (template) {
                $("#production-table tbody").append(template);
                $(".date").mask("99/99/9999");
                $(".time").mask("99:99");
            });
        });

        $("#WorkshopId").change(function () {
            ReloadWorkshopLines($(this).val());
        });

        $(document).ready(function () {
            $(".date").mask("99/99/9999");
            $(".time").mask("99:99");
        });
    </script>
}

SopEmbraco/Views/Productions/Delete.cshtml
@model SopEmbraco.Models.Production

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Production</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductionBatch.BatchNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductionBatch.BatchNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkshopLine.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkshopLine.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Target)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Target)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RealQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RealQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SopEmbraco/Views/Productions/Details.cshtml
@model SopEmbraco.Models.WorkshopLine

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<h3>Workshop: @Model.Workshop.Name</h3>
<table class="table">
    <tr>
        <td>
            <table class="table">
                <tr>
                    <th>
                        Production Batch
                    </th>
                    <th>
                        Product Code
                    </th>
                    <th>
                        Workshop Line
                    </th>
                    <th>
                        Date
                    </th>
                    <th>
                        Start Time
                    </th>
                    <th>
                        End Time
                    </th>
                    <th>
                        Target
                    </th>
                    <th>
                        Real Quantity
                    </th>
                    <th>
                        Real Quantity Batch
                    </th>
                    <th>
                        Comment
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model.Productions)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductionBatch.BatchNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductionBatch.ProductCode.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.WorkshopLine.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EndTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Target)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RealQuantity)
                        </td>
                        <td>
                            @Model.Productions.Where(p => p.ProductionBatchId == item.ProductionBatchId).Sum(p => p.RealQuantity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Comment)
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", new { id = item.ProductionId })
                        </td>
                    </tr>
                }
            </table>
        </td>
    </tr>
</table>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.WorkshopLineId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SopEmbraco/Views/Productions/_CreateOrEdit.cshtml
@model SopEmbraco.ViewModels.ProductionViewModel

<div class="form-group">
    <table class="table" id="production-table">
        <thead>
            <tr>
                <th>Production Batch</th>
                <th>Plan Qty.</th>
                <th>Product Code</th>
                <th>Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Target</th>
                <th>Real Quantity</th>
                <th>Comment</th>
                <th style="min-width: 176px;">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.PendingProductions != null)
            {
                foreach (var production in Model.PendingProductions)
                {
                    @Html.Partial("_ProductionRow", production)
                }
            }
        </tbody>
    </table>
</div>

SopEmbraco/Views/Productions/_ProductionRow.cshtml
@model SopEmbraco.Models.Production
@using SopEmbraco.Models

<tr>
    @using (Html.BeginCollectionItem("PendingProductions"))
    {
        @Html.HiddenFor(model => model.WorkshopLineId)
        @Html.HiddenFor(model => model.ProductionId)

        <td class="form-group">
            @if (Model.ProductionBatchStatusConcluded)
            {
                @Html.HiddenFor(model => model.ProductionBatchId)
                @Html.TextBoxFor(model => model.ConcludedBatchName, new { @class = "form-control", @readonly = "readonly" })
            }
            else
            {
                @Html.DropDownListFor(model => model.ProductionBatchId, ((IEnumerable<ProductionBatch>)ViewBag.ProductionBatches).Select(option => new SelectListItem
                {
                    Text = option.BatchNumber,
                    Value = option.ProductionBatchId.ToString(),
                    Selected = (Model != null) && (Model.ProductionBatchId == option.ProductionBatchId)
                }), "Select...", new { @class = "form-control productionbatch", style = "min-width: 100px;" })
            }

            @Html.ValidationMessageFor(model => model.ProductionBatchId, "", new { @class = "text-danger" })
        </td>

        <td class="form-group">
            @Html.EditorFor(model => model.PlanQuantity, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", style = "min-width: 80px;" } })
        </td>

        <td class="form-group">
            @Html.EditorFor(model => model.ProductCodeName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", style = "min-width: 120px;" } })
        </td>

        <td class="form-group">
            @Html.TextBoxFor(model => model.Date, "{0:dd/MM/yyyy}", new { @class = "form-control date", style = "min-width: 100px;" })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </td>

        <td class="form-group">
            @Html.TextBoxFor(model => model.StartTime, new { @class = "form-control time", style = "min-width: 100px;" })
            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
        </td>

        <td class="form-group">
            @Html.TextBoxFor(model => model.EndTime, new { @class = "form-control time", style = "min-width: 100px;" })
            @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
        </td>

        <td class="form-group">
            @Html.EditorFor(model => model.Target, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", style = "min-width: 80px;" } })
            @Html.ValidationMessageFor(model => model.Target, "", new { @class = "text-danger" })
        </td>

        <td class="form-group">
            @Html.EditorFor(model => model.RealQuantity, new { htmlAttributes = new { @class = "form-control", style = "min-width: 80px;" } })
            @Html.ValidationMessageFor(model => model.RealQuantity, "", new { @class = "text-danger" })
        </td>

        <td class="form-group">
            @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control", rows = 1, style = "min-width: 130px;" } })
            @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
        </td>

        <td>
            <a class="btn btn-default" onclick="$(this).parent().parent().remove();">Delete</a>
            <a class="btn btn-success save-line">Save</a>
        </td>
    }
</tr>